# Generated by Django 5.0.6 on 2024-05-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomer',
            new_name='Customer',
        ),
    ]
